name: Check code health

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python@v3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Setup project
        run: make setup

      - name: Run tests
        run: make test

  Build:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: Setup python@v3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Setup project
        run: make setup

      - name: Build application
        run: make build
